services:

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=health
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
#    build:
#      dockerfile: ./Dockerfile
#      context: .
    image: shvedfun/health_web:0.1
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
      - ./media:/app/media
    environment:
      - DB_NAME=health
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn -c ./gunicorn.conf.py project.wsgi

  nginx:
    build: ./nginx
#    image: shvedfun/health_nginx:0.1
    volumes:
      - ./static:/static
    ports:
      - 80:8080
    depends_on:
      - web

volumes:
  pgdata:
