services:

 # db:
 #   image: postgres
 #   ports:
 #     - '5432:5432'
 #   volumes:
 #     - pgdata:/var/lib/postgresql/data
 #   environment:
 #     - POSTGRES_DB=health
 #     - POSTGRES_USER=postgres
 #     - POSTGRES_PASSWORD=postgres

  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: oncore_back_web
    ports:
      - '8000:8000'
#    depends_on:
#      - db
    volumes:
#      - ${APP_VOLUME:-/dev/null:/dev/null}
      - ./static:/app/staticfiles
      - ./media:/app/media
    environment:
      - DB_NAME=health
      - DB_USER=postgres
      - DB_PASSWORD=afaFA!911
      - DB_HOST=172.28.66.97
      - DB_PORT=30010
    command: ["bash", "-c", "python manage.py collectstatic --noinput && sleep 5 && gunicorn -c ./gunicorn.conf.py project.wsgi"]

  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    ports:
      - 1337:80
    depends_on:
      - web



#volumes:
#  pgdata:
