apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: repo.oncor.pro/health_region/health_web
        envFrom:
        - secretRef:
          name: secrets-health-region
        volumeMounts:
        - mountPath: /app/staticfiles
          name: static-volume
        - mountPath: /app/media
          name: media-volume
        command: ["gunicorn", "-c", "./gunicorn.conf.py", "project.wsgi"]
#        imagePullSecrets:
#          - name: nexus-secret
      volumes:
      - name: static-volume
        hostPath:
          path: /app/static  
      - name: media-volume
        hostPath:
          path: /app/media  
      imagePullSecrets:
        - name: nexus-secret
