# Generated by Django 5.0.6 on 2024-07-09 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0009_person_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.JSONField(verbose_name='Распределение популяции')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('generate_at', models.DateTimeField(blank=True, null=True, verbose_name='Время генерации данных')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_region', to='health.region', verbose_name='Регион')),
            ],
        ),
    ]
