# Generated by Django 5.0.6 on 2024-08-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_generator', '0002_regiondirectiongeneratedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regiondirectiongeneratedata',
            old_name='date',
            new_name='load_date',
        ),
        migrations.AddField(
            model_name='regiondirectiongeneratedata',
            name='year',
            field=models.PositiveIntegerField(null=True, verbose_name='Год'),
        ),
    ]
