# Generated by Django 5.0.6 on 2024-07-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('М', 'Man'), ('Ж', 'Woman')], max_length=1, verbose_name='Пол')),
                ('birthday', models.DateTimeField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Гражданин',
                'verbose_name_plural': 'Граждане',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Регион')),
                ('code', models.CharField(max_length=2, verbose_name='Код региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Группа населения',
                'verbose_name_plural': 'Группы населения',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Заболевание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.direction', verbose_name='Направление заболевания')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Обследование')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_direction', to='health.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Обследование',
                'verbose_name_plural': 'Обследования',
            },
        ),
        migrations.CreateModel(
            name='ExaminationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Плановая дата обследования')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин')),
            ],
            options={
                'verbose_name': 'План обследования',
                'verbose_name_plural': 'Планы обследований',
            },
        ),
        migrations.CreateModel(
            name='ExaminationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.JSONField(verbose_name='Схема обследования')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование')),
            ],
            options={
                'verbose_name': 'Схема обследования',
                'verbose_name_plural': 'Схемы обследований',
            },
        ),
        migrations.CreateModel(
            name='ExaminationFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Фактическая дата обследования')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование')),
                ('examination_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination_plan', to='health.examinationplan', verbose_name='Плановое обследование')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин')),
            ],
            options={
                'verbose_name': 'Проведенное обследование',
                'verbose_name_plural': 'Проведенные обследования',
            },
        ),
        migrations.CreateModel(
            name='PersonDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_from', models.DateTimeField(verbose_name='Дата диагноза')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_disease', to='health.disease', verbose_name='Заболевание')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_state', to='health.state', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заболевание гражданина',
                'verbose_name_plural': 'Заболевания граждан',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='%(model_name)s_from_Disease', through='health.PersonDisease', to='health.disease', verbose_name='Заболевания'),
        ),
    ]
