# Generated by Django 5.0.6 on 2024-07-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='person',
            table_comment='Гражданин',
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(db_comment='Дата рождения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('М', 'Man'), ('Ж', 'Woman')], db_comment='Пол', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_comment='ФИО', max_length=200, verbose_name='ФИО'),
        ),
    ]
