# Generated by Django 5.0.6 on 2024-07-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_alter_person_table_comment_alter_person_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='direction',
            table_comment='Направление',
        ),
        migrations.AlterModelTableComment(
            name='disease',
            table_comment='Заболевание',
        ),
        migrations.AlterModelTableComment(
            name='examination',
            table_comment='Обследование',
        ),
        migrations.AlterModelTableComment(
            name='examinationfact',
            table_comment='Проведенное обследование',
        ),
        migrations.AlterModelTableComment(
            name='examinationplan',
            table_comment='План обследования',
        ),
        migrations.AlterModelTableComment(
            name='examinationscheme',
            table_comment='Схема обследования',
        ),
        migrations.AlterModelTableComment(
            name='persondisease',
            table_comment='Заболевание гражданина',
        ),
        migrations.AlterModelTableComment(
            name='region',
            table_comment='Регион',
        ),
        migrations.AddField(
            model_name='persondisease',
            name='finish_at',
            field=models.DateTimeField(blank=True, db_comment='Дата окончания', null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(db_comment='Наименование', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='direction',
            field=models.ForeignKey(db_comment='Направление заболевания', on_delete=django.db.models.deletion.CASCADE, to='health.direction', verbose_name='Направление заболевания'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(db_comment='Заболевание', max_length=1000, verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='direction',
            field=models.ForeignKey(db_comment='Направление', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_direction', to='health.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(db_comment='Обследование', max_length=1000, verbose_name='Обследование'),
        ),
        migrations.AlterField(
            model_name='examinationfact',
            name='date',
            field=models.DateField(db_comment='Фактическая дата обследования', verbose_name='Фактическая дата обследования'),
        ),
        migrations.AlterField(
            model_name='examinationfact',
            name='examination',
            field=models.ForeignKey(db_comment='Обследование', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование'),
        ),
        migrations.AlterField(
            model_name='examinationfact',
            name='examination_plan',
            field=models.ForeignKey(blank=True, db_comment='Плановое обследование', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination_plan', to='health.examinationplan', verbose_name='Плановое обследование'),
        ),
        migrations.AlterField(
            model_name='examinationfact',
            name='person',
            field=models.ForeignKey(db_comment='Гражданин', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин'),
        ),
        migrations.AlterField(
            model_name='examinationplan',
            name='date',
            field=models.DateField(db_comment='Плановая дата обследования', verbose_name='Плановая дата обследования'),
        ),
        migrations.AlterField(
            model_name='examinationplan',
            name='examination',
            field=models.ForeignKey(db_comment='Обследование', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование'),
        ),
        migrations.AlterField(
            model_name='examinationplan',
            name='person',
            field=models.ForeignKey(db_comment='Гражданин', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин'),
        ),
        migrations.AlterField(
            model_name='examinationscheme',
            name='examination',
            field=models.ForeignKey(db_comment='Обследование', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_examination', to='health.examination', verbose_name='Обследование'),
        ),
        migrations.AlterField(
            model_name='examinationscheme',
            name='scheme',
            field=models.JSONField(db_comment='Схема обследования', verbose_name='Схема обследования'),
        ),
        migrations.AlterField(
            model_name='persondisease',
            name='disease',
            field=models.ForeignKey(db_comment='Заболевание', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_disease', to='health.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='persondisease',
            name='person',
            field=models.ForeignKey(db_comment='Гражданин', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_person', to='health.person', verbose_name='Гражданин'),
        ),
        migrations.AlterField(
            model_name='persondisease',
            name='start_from',
            field=models.DateTimeField(db_comment='Дата диагноза', verbose_name='Дата диагноза'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_comment='Код региона', max_length=2, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(db_comment='Регион', max_length=100, verbose_name='Регион'),
        ),
    ]
