# Generated by Django 5.0.6 on 2024-07-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_alter_direction_table_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Этап', max_length=100, verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Этап заболевания',
                'verbose_name_plural': 'Этапы заболеваний',
                'db_table_comment': 'Этап заболевания',
            },
        ),
        migrations.RemoveField(
            model_name='persondisease',
            name='state',
        ),
        migrations.AddField(
            model_name='persondisease',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_stage', to='health.stagedisease', verbose_name='Этап'),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
