# Generated by Django 5.0.6 on 2024-07-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_person_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(db_comment='Дата рождения', verbose_name='Дата рождения'),
        ),
    ]
