# Generated by Django 5.0.6 on 2024-07-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_alter_person_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(db_comment='Код региона', max_length=2, primary_key=True, serialize=False, verbose_name='Код региона'),
        ),
    ]
