# Generated by Django 5.0.6 on 2024-07-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_remove_person_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.ForeignKey(db_comment='Регион', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_region', to='health.region', verbose_name='Регион'),
        ),
    ]
