# Generated by Django 5.0.6 on 2024-07-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_person_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Наименование', max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория заболевания',
                'verbose_name_plural': 'Категории заболеваний',
                'db_table_comment': 'Категория заболевания',
            },
        ),
        migrations.AlterField(
            model_name='disease',
            name='direction',
            field=models.ForeignKey(db_comment='Направление заболевания', on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_direction', to='health.direction', verbose_name='Направление заболевания'),
        ),
        migrations.AddField(
            model_name='disease',
            name='category',
            field=models.ForeignKey(db_comment='Категория', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(model_name)s_from_category', to='health.diseasecategory', verbose_name='Категория'),
        ),
    ]
