# Generated by Django 5.0.6 on 2024-07-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_diseasecategory_alter_disease_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='direction',
        ),
        migrations.AddField(
            model_name='examination',
            name='disease',
            field=models.ForeignKey(db_comment='Заболевание', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_disease', to='health.disease', verbose_name='Заболевание'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='name',
            field=models.CharField(db_comment='Обследование', max_length=200, verbose_name='Обследование'),
        ),
    ]
