# Generated by Django 5.0.6 on 2024-07-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_alter_applicability_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationplan',
            old_name='date',
            new_name='date_on',
        ),
    ]
