# Generated by Django 5.0.6 on 2024-07-27 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_rename_date_examinationplan_date_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionDirectionGenerateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('type', models.CharField(choices=[('population', 'Population'), ('plan', 'Plan'), ('fact', 'Fact')], max_length=10, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('data', models.JSONField(verbose_name='Данные')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_direction', to='health.direction', verbose_name='Направление медицины')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_region', to='health.region', verbose_name='Регион')),
            ],
        ),
    ]
