# Generated by Django 5.0.6 on 2024-07-28 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_regiondirectiongeneratedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiondirectiongeneratedata',
            options={'verbose_name': 'Данные для генерации распределений', 'verbose_name_plural': 'Данные для генерации распределений'},
        ),
        migrations.AlterField(
            model_name='regiondirectiongeneratedata',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_direction', to='health.direction', verbose_name='Направление медицины'),
        ),
        migrations.AlterField(
            model_name='regiondirectiongeneratedata',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(model_name)s_from_region', to='health.region', verbose_name='Регион'),
        ),
    ]
