# Generated by Django 5.0.6 on 2024-07-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_alter_regiondirectiongeneratedata_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionDirectionGenerateData',
        ),
    ]
