# Generated by Django 5.0.6 on 2024-08-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_delete_regiondirectiongeneratedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationfact',
            name='examination_plan',
            field=models.ForeignKey(blank=True, db_comment='Плановое обследование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(model_name)s_from_examination_plan', to='health.examinationplan', verbose_name='Плановое обследование'),
        ),
    ]
