# Generated by Django 5.0.6 on 2024-08-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_alter_examinationfact_examination_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Наименование', max_length=200, verbose_name='Наименование')),
                ('region', models.ForeignKey(db_comment='Регион', on_delete=django.db.models.deletion.PROTECT, to='health.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'db_table_comment': 'Район',
            },
        ),
        migrations.CreateModel(
            name='MedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='Наименование', max_length=200, verbose_name='Наименование')),
                ('district', models.ForeignKey(db_comment='Район', on_delete=django.db.models.deletion.PROTECT, to='health.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Мед.организация',
                'verbose_name_plural': 'Мед.организация',
                'db_table_comment': 'Мед.организация',
            },
        ),
    ]
