# Generated by Django 5.0.6 on 2024-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_district_medorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='gender',
            field=models.CharField(choices=[('М', 'Man'), ('Ж', 'Woman'), ('МЖ', 'All')], db_comment='Пол', default='МЖ', max_length=2, verbose_name='Пол'),
        ),
    ]
