# Generated by Django 5.1.1 on 2024-09-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_medorganization_factor_alter_examination_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='med_org',
            field=models.ForeignKey(db_comment='Мед.организация', null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.medorganization', verbose_name='Мед.организация'),
        ),
    ]
